### PR TITLE
Push docker-image on merge to main

### PR DESCRIPTION
**Pull request by volovyks**
In the FastAuth project, we want to move from using the `latest` sandbox to a fixed version. This PR should help to automate it. I don't know what is the release strategy now, we can tune how it's triggered.
`aarch` is not automated, not sure if that is possible now.

### CODE REVIEW

**Review by ChaoticTempest — APPROVED** [review]

**Review by frol — APPROVED** [review]
Looks good to me 👍

**Comment by frol** [comment]
@volovyks It failed: https://github.com/near/sandbox/actions/runs/6870888779/job/18686664253

I guess you need to add permissions to the workflow file: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by itegulov** [comment]
@frol Added write permissions for this repo and also you as an admin to the package, hth

**Comment by frol** [comment]
@itegulov Where did you add it to? I don't see any new PRs and commits to main.

**Comment by itegulov** [comment]
@frol it's just a package under NEAR org: https://github.com/orgs/near/packages/container/package/sandbox

**Comment by frol** [comment]
@itegulov Ah, I see now, I just needed to re-run CI: https://github.com/near/sandbox/actions/runs/6870888779/job/18725832049, it passes now.

**Pull request merged**
