### PR TITLE
Native support M1

### PR DESCRIPTION
**Pull request by paulo20223**
I think it's only tmp version.

### CODE REVIEW

**Comment by joshuajbouw** [comment]
Do note #42 which has a change to `getBinary.ts` file which should also be updated.

**Comment by paulo20223** [comment]
Greate. I can do it.

**Comment by paulo20223** [comment]
@joshuajbouw I added update to npm

**Comment by ChaoticTempest** [comment]
Hey, thanks for the PR, but this is not ideal to add quite yet, since the binary being provided is just a temporary one. The rust/crate needs the ability to select the version based on the commit hash into nearcore, which the pipeline is not setup to do yet. Also, we'd need to have alignment on the version since the temp one is not the same version as the one being referenced by `{linux, mac}x86_64`. So, I'm gonna hold off from reviewing/merging this one in until then

**Comment by paulo20223** [comment]
@ChaoticTempest Maybe i will send issue for nearcore. I found the branch VLAD-test in nearcore. The gitflow was added in master and it has worked only on branch VLAD-test.

**Comment by ChaoticTempest** [comment]
@paulo20223 that's actually the test branch for the pipeline, so they're definitely working on it right now. No need to write an issue in nearcore

**Comment by ChaoticTempest** [comment]
closing this one since M1 is now in sandbox

**Pull request closed without merging**
